# Generated by Django 4.0.4 on 2022-05-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tag_order_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tags',
            new_name='tag',
        ),
    ]
